queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: "<img src=x onerror=alert(document.domain)>"
    conditions:
      - base=main
    actions:
      queue:
        name: default
